version: '3.8'

services:
  app1:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: "app"
      SPRING_DATA_MONGODB_URI: "mongodb://banco1:27017,banco2:27017,banco3:27017,banco4:27017,banco5:27017/db_dsid?replicaSet=cenAdm&readPreference=nearest"
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    networks:
      - mongo-cluster
  app2:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: "app"
      SPRING_DATA_MONGODB_URI: "mongodb://banco1:27017,banco2:27017,banco3:27017,banco4:27017,banco5:27017/db_dsid?replicaSet=cenAdm&readPreference=nearest"
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    networks:
      - mongo-cluster
  app3:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: "app"
      SPRING_DATA_MONGODB_URI: "mongodb://banco1:27017,banco2:27017,banco3:27017,banco4:27017,banco5:27017/db_dsid?replicaSet=cenAdm&readPreference=nearest"
    depends_on:
      mongo-setup:
        condition: service_completed_successfully
    networks:
      - mongo-cluster

  load-balancer:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=lb
    ports:
      - "8080:8080"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - mongo-cluster

  banco1:
    image: mongo:latest
    container_name: banco1
    command: ["mongod", "--replSet", "cenAdm", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - banco1_data:/data/db
    networks:
      - mongo-cluster

  banco2:
    image: mongo:latest
    container_name: banco2
    command: ["mongod", "--replSet", "cenAdm", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - banco2_data:/data/db
    networks:
      - mongo-cluster

  banco3:
    image: mongo:latest
    container_name: banco3
    command: ["mongod", "--replSet", "cenAdm", "--bind_ip_all"]
    ports:
      - "27019:27017"
    volumes:
      - banco3_data:/data/db
    networks:
      - mongo-cluster

  banco4:
    image: mongo:latest
    container_name: banco4
    command: ["mongod", "--replSet", "cenAdm", "--bind_ip_all"]
    ports:
      - "27020:27017"
    volumes:
      - banco4_data:/data/db
    networks:
      - mongo-cluster

  banco5:
    image: mongo:latest
    container_name: banco5
    command: ["mongod", "--replSet", "cenAdm", "--bind_ip_all"]
    ports:
      - "27021:27017"
    volumes:
      - banco5_data:/data/db
    networks:
      - mongo-cluster

  # --- O CONTAINER DE AUTOMAÇÃO ---
  mongo-setup:
    image: mongo:latest
    container_name: mongo-setup
    depends_on:
      - banco1
      - banco2
      - banco3
      - banco4
      - banco5

    volumes:
      - ./Mongodb.js:/scripts/Mongodb.js:ro,Z
    networks:
      - mongo-cluster
    command: >
      bash -c "
        echo 'Aguardando 10s para os bancos iniciarem...';
        sleep 10;
        
        echo 'Iniciando a configuração do Replica Set...';
        mongosh --host banco1:27017 --eval 'rs.initiate({
          _id: \"cenAdm\",
          members: [
            { _id: 0, host: \"banco1:27017\", priority: 4 },
            { _id: 1, host: \"banco2:27017\", priority: 3 },
            { _id: 2, host: \"banco3:27017\", priority: 2 },
            { _id: 3, host: \"banco4:27017\", priority: 2 },
            { _id: 4, host: \"banco5:27017\", priority: 1 }
          ]
        })';
        
        echo 'Aguardando 10s para a eleição do Primário terminar...';
        sleep 10;
        
        echo 'Rodando o arquivo Mongodb.js para popular o banco...';
        mongosh --host banco1:27017 /scripts/Mongodb.js;
        
        echo 'Tudo pronto! O banco do Cactoflix está configurado e populado.';
      "

networks:
  mongo-cluster:
    driver: bridge

volumes:
  banco1_data:
  banco2_data:
  banco3_data:
  banco4_data:
  banco5_data: