# Sem Profile (App)
spring:
  application:
    name: cactoflix
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://localhost:27017,localhost:27018,localhost:27019,localhost:27020,localhost:27021/db_dsid?replicaSet=cenAdm&readPreference=nearest}

---
# Com Profile (LB)
spring:
  config:
    activate:
      on-profile: lb
  autoconfigure:
    exclude:
      - org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration
      - org.springframework.boot.data.mongodb.autoconfigure.DataMongoAutoConfiguration
